services:
  api:
    build: ./backend
    env_file: ./backend/.env.docker
    ports:
      - "3000:3000"
    depends_on:
      - mongo
  mongo:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db

volumes: { mongodata: {} }
